// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<SpeedController> RobotMap::driveTrainTopRight;
std::shared_ptr<SpeedController> RobotMap::driveTrainTopLeft;
std::shared_ptr<SpeedController> RobotMap::driveTrainBottomRight;
std::shared_ptr<SpeedController> RobotMap::driveTrainBottomLeft;
std::shared_ptr<SpeedController> RobotMap::driveTrainCenter;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    driveTrainTopRight.reset(new Talon(0));
    lw->AddActuator("DriveTrain", "TopRight", std::static_pointer_cast<Talon>(driveTrainTopRight));
    
    driveTrainTopLeft.reset(new Talon(1));
    lw->AddActuator("DriveTrain", "TopLeft", std::static_pointer_cast<Talon>(driveTrainTopLeft));
    
    driveTrainBottomRight.reset(new Talon(2));
    lw->AddActuator("DriveTrain", "BottomRight", std::static_pointer_cast<Talon>(driveTrainBottomRight));
    
    driveTrainBottomLeft.reset(new Talon(3));
    lw->AddActuator("DriveTrain", "BottomLeft", std::static_pointer_cast<Talon>(driveTrainBottomLeft));
    
    driveTrainCenter.reset(new Talon(4));
    lw->AddActuator("DriveTrain", "Center", std::static_pointer_cast<Talon>(driveTrainCenter));
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
