// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVETRAIN_H
#define DRIVETRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author Garrick Craft
 */

class DriveTrain: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities

	std::shared_ptr<SpeedController> topRight;
	std::shared_ptr<SpeedController> topLeft;
	std::shared_ptr<SpeedController> bottomRight;
	std::shared_ptr<SpeedController> bottomLeft;
	std::shared_ptr<SpeedController> center;


public:

	enum DriveMotor
	{
		TOP_RIGHT,
		TOP_LEFT,
		CENTER,
		BOTTOM_RIGHT,
		BOTTOM_LEFT
	};

	DriveTrain();

	void InitDefaultCommand();

	void SetMotorSpeed(DriveMotor motor, double speed);

	void StopMoving();

};

#endif
