// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "DriveTrain.h"
#include "../RobotMap.h"
#include "../Commands/DriveTeleop.h"



DriveTrain::DriveTrain() : Subsystem("DriveTrain") {

    topRight = RobotMap::driveTrainTopRight;
    topLeft = RobotMap::driveTrainTopLeft;
    bottomRight = RobotMap::driveTrainBottomRight;
    bottomLeft = RobotMap::driveTrainBottomLeft;
    center = RobotMap::driveTrainCenter;

}

void DriveTrain::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());

        SetDefaultCommand(new DriveTeleop(0, 0, 0));


}

// Put methods for controlling this subsystem
// here. Call these from Commands.

void DriveTrain::SetMotorSpeed(DriveTrain::DriveMotor motor, double speed)
{
	switch (motor)
	{
		case(DriveTrain::TOP_LEFT):
		{
			DriveTrain::topLeft->Set(speed);
			break;
		}
		case(DriveTrain::TOP_RIGHT):
		{
			DriveTrain::topRight->Set(speed);
			break;
		}
		case(DriveTrain::CENTER):
		{
			DriveTrain::center->Set(speed);
			break;
		}
		case(DriveTrain::BOTTOM_LEFT):
		{
			DriveTrain::bottomLeft->Set(speed);
			break;
		}
		case(DriveTrain::BOTTOM_RIGHT):
		{
			DriveTrain::bottomRight->Set(speed);
			break;
		}
		default:
			return;
	}
}

void DriveTrain::StopMoving()
{
	DriveTrain::topRight->Set(0.0);
	DriveTrain::topLeft->Set(0.0);
	DriveTrain::center->Set(0.0);
	DriveTrain::bottomLeft->Set(0.0);
	DriveTrain::bottomRight->Set(0.0);
}

